name: Deploy Flask App to ECS

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image to ECR
        run: |
          IMAGE_TAG=latest
          ECR_URL=877407756445.dkr.ecr.ap-south-1.amazonaws.com/ecs-loki-demo-repo
          
          echo "Building Docker image..."
          docker build --platform linux/amd64 -t $ECR_URL:$IMAGE_TAG .
          
          echo "Pushing Docker image..."
          docker push $ECR_URL:$IMAGE_TAG

      - name: Force new ECS deployment
        run: |
          aws ecs update-service \
            --cluster ecs-loki-demo-cluster \
            --service ecs-loki-demo-service \
            --force-new-deployment
